theme: jekyll-theme-minimal
title: Some notes on Java EE and React
description: Hi, I'm Marek Switajski - a Java EE and ReactJS developer. Here I'm providing some notes on my experiences when programming.